### ISSUE TITLE
cannot load a larger initramfs

### ISSUE THREAD

**Issue by jyf007** [ipxe/ipxe#151] opened 2020-10-01 10:17 UTC
platform:qemu and deskmini H110/COM
cpu i7-7700
ram up to 32 gig

i build a ipxe http boot site at links below
http://xz-nat.uovz.com:10423/
with 8 script from menu0.ipxe to menu7.ipxe
but i always failed with a large initramfs to unpack to boot entire linux distro system in ram.

**Comment by NiKiZe** [comment] 2020-10-01 14:14
Any error message?
Running pcbios or efi?

**Comment by jyf007** [comment] 2020-10-02 07:21
qemu doesn't show anything
deskmini cannot shot a screenshot, just VFS mount error

**Comment by jyf007** [comment] 2020-10-02 07:21
both of platform is uefi

**Comment by NiKiZe** [comment] 2020-10-02 07:26
There is not enough information here to try and help you.
General VFS errors is most of the time due to incorrect scripts or init files. and no information has been provided around that at all.

The FAQ on the forum probably have this case covered.

**Comment by NiKiZe** [comment] 2020-10-02 15:02
I will close this issue since there is no evidence that this is an issue with iPXE itself.
If there is more information to reproduce this, such as ipxe script and all other needed files, then we will reopen.

**Closed by NiKiZe** 2020-10-02 15:02 UTC

**Comment by jyf007** [comment] 2020-10-03 23:46
i have shoted the pictures
![IMG_20201004_073842](https://user-images.githubusercontent.com/17245835/95003797-b70b8f00-0615-11eb-85d2-84c925b103f3.jpg)
![IMG_20201004_074204](https://user-images.githubusercontent.com/17245835/95003798-b96de900-0615-11eb-9dc1-a003fbc7d2fd.jpg)
![IMG_20201004_074225](https://user-images.githubusercontent.com/17245835/95003799-bbd04300-0615-11eb-9591-3829ec2e0e31.jpg)

**Comment by NiKiZe** [comment] 2020-10-04 01:01
Still No script, does the same files work if you boot locally with say grub from usb? Also does your kernel have the compression algo supported?

**Comment by jyf007** [comment] 2020-10-04 04:59
the context in menu0.ipxe file is here:
#!ipxe
kernel vmlinuz-linux-ramos
initrd rootfs-openrc-base.cpio.lz4
boot
and grub with x86_64-efi work proper

**Comment by mcb30** [comment] 2020-10-04 21:02
@jyf007 You will need to add `initrd=rootfs-openrc-base.cpio.lz4` to your kernel command line to tell it which file to open as the initramfs image.  For example:

```
#!ipxe
kernel vmlinuz-linux-ramos initrd=rootfs-openrc-base.cpio.lz4
initrd rootfs-openrc-base.cpio.lz4
boot
```

Also, you are using what looks to be a very old version of iPXE: please consider using an up-to-date version.

**Comment by jyf007** [comment] 2020-10-05 06:36
thanks,and up to date version is always building failed

**Comment by jyf007** [comment] 2020-10-05 12:32
well,i tried the up-to-date version,and failed

**Comment by jyf007** [comment] 2020-10-08 05:46
update -- failed in qemu
