### ISSUE TITLE
realtek 8168/8169 doesn't work

### ISSUE THREAD

**Issue by skeletorgithub** [ipxe/ipxe#1281] opened 2024-08-22 11:32 UTC
Hello.
We have a box with motherboard asrock j4125b-itx with embedded NIC, which detected by LiveCD as:
```
02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)

driver: r8169
version: 6.1.0-22-amd64
firmware-version: rtl8168h-2_0.0.2 02/26/15
expansion-rom-version: 
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```
but it doesn't detect by iPXE (we use 1.21.1):
```
downloading NBP file ok
autoexec.ipxe ok
debug(pci):
(10ec:8168) has driver "rtl8168"
...
probe failed: Connection timed out
```
According to hardware list, this NIC supported by iPXE. Also, I've tried to change in sources to force using driver r8169, but it didn't help.
```
iPXE initialising devices...Adding 3c509 root bus
Adding EFI root bus
0000:02:00.0 (10ec:8168) has driver "rl18169"
0000:02:00.0 has mem a1004000 io e000 irq 255
0000:02:00.0 latency timer is unreasonably low at 0. Setting to 32.
0000:02:00.0 probe failed: Connection timed out (https://ipxe.org/4c634092)
```

Could you help me?

_Originally posted by @skeletorgithub in https://github.com/ipxe/ipxe/discussions/1280_

**Comment by mcb30** [comment] 2024-08-22 12:05
Duplicate of #1280

**Closed by mcb30** 2024-08-22 12:05 UTC
