### ISSUE TITLE
make CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 bin-arm64-efi/ipxe.efi EMBED=boot.ipxe -C ipxe/src && cp ipxe/src/bin-x86_64-efi/ipxe.efi /var/lib/tftpboot/arm_uefi/

### ISSUE THREAD

**Issue by lx775289883** [ipxe/ipxe#1090] opened 2023-11-30 10:02 UTC
[BUILD] bin-arm64-efi/amd8111e.ids.o
[BUILD] bin-arm64-efi/intel.ids.o
[BUILD] bin-arm64-efi/rhine.ids.o
[BUILD] bin-arm64-efi/intelxl.ids.o
[BUILD] bin-arm64-efi/eepro100.ids.o
[BUILD] bin-arm64-efi/smc9000.ids.o
[BUILD] bin-arm64-efi/pcnet32.ids.o
[BUILD] bin-arm64-efi/3c509-eisa.ids.o
[BUILD] bin-arm64-efi/b44.ids.o
[BUILD] bin-arm64-efi/thunderx.ids.o
[BUILD] bin-arm64-efi/igbvf_main.ids.o
[BUILD] bin-arm64-efi/phantom.ids.o
[BUILD] bin-arm64-efi/vxge.ids.o
[BUILD] bin-arm64-efi/tg3.ids.o
[BUILD] bin-arm64-efi/bnxt.ids.o
[BUILD] bin-arm64-efi/sfc_hunt.ids.o
[BUILD] bin-arm64-efi/linda.ids.o
[BUILD] bin-arm64-efi/hermon.ids.o
[BUILD] bin-arm64-efi/arbel.ids.o
[BUILD] bin-arm64-efi/qib7322.ids.o
[BUILD] bin-arm64-efi/golan.ids.o
[BUILD] bin-arm64-efi/xhci.ids.o
[BUILD] bin-arm64-efi/uhci.ids.o
[BUILD] bin-arm64-efi/ehci.ids.o
[BUILD] bin-arm64-efi/rtl8185.ids.o
[BUILD] bin-arm64-efi/rtl8180.ids.o
[BUILD] bin-arm64-efi/ath5k.ids.o
[BUILD] bin-arm64-efi/ath9k.ids.o
[AR] bin-arm64-efi/blib.a
[HOSTCC] util/elf2efi64
[VERSION] bin-arm64-efi/version.ipxe.efi.o
[LD] bin-arm64-efi/ipxe.efi.tmp
bin-arm64-efi/blib.a(config.o): In function __requiring_symbol__': config.c:(.tbl.requiring_symbols+0x0): undefined reference to obj_video_subr'
make: *** [bin-arm64-efi/ipxe.efi.tmp] Error 1
rm bin-arm64-efi/version.ipxe.efi.o
make: Leaving directory `/home/ipxe/src'

**Comment by NiKiZe** [comment] 2023-12-01 10:28
Duplicate of #1088

**Closed by NiKiZe** 2023-12-01 10:28 UTC
