### ISSUE TITLE
ipxe.efi works with ${next-server} option while undionly.kpxe doesn't

### ISSUE THREAD

**Issue by bcb01** [ipxe/ipxe#517] opened 2021-11-13 17:35 UTC
Hi guys, 

I need some help to get my BIOS/UEFI PXE server running. I set it up with dnsmasq (proxy mode), ipxe.efi and undionly.kpxe, both using the same boot script later on. Serving works fine in terms of delivering the right file to the specific (BIOS or UEFI) client. From there on it gets a little weird. While ipxe.efi finds its boot server and script automatically from the DHCP options (${next-server} and ${filename}) and after that starts the desired OS as intended, undionly.kpxe doesn't find or boot anything at all.
To get this done, I need to specify the PXE server IP and the boot script location in static form in an embedded script, and after that I need to do the same in the boot script to be able to load the OSes. The config tool in the ipxe shell shows the "next-server" and "filename" options populated with an IP and a path in the UEFI version (ipxe.efi), but unpopulated in the BIOS version (undionly.kpxe). So dnsmasq seems to deliver it but undionly.kpxe doesn't receive or interpret it and is therefore unable to use this info later on, which leads to the described behaviour.

This is a bit annoying, because I want to use the PXE server in different networks and don't want to alter the related scripts and build a new undionly.kpxe every time.

Did I miss something or is this the desired behaviour? If so, how can I get around this issue without changing scripts for every new network (DHCP) setting? Would be nice if someone out there could point me in the right direction to get this issue sorted. Thx in advance. 

Chris

PS: I'm not sure if this is the same issue as in [this](https://github.com/ipxe/ipxe/issues/144) and [this](https://github.com/ipxe/ipxe/issues/482) post.

Attachments:
![dnsmasq conf](https://user-images.githubusercontent.com/94238673/141654426-b668b835-3698-4c08-88b0-4bcda5dd70ac.jpg)
dnsmasq.conf

![dnsmasq-log](https://user-images.githubusercontent.com/94238673/141976085-30d4a800-d64a-476b-b9f3-72e0470e11a1.jpg)
dnsmasq-log (shows that server and filename are getting delivered)

![undionly kpxe](https://user-images.githubusercontent.com/94238673/141654449-7d3c8c45-2547-40e4-ade9-e375a05fff7d.jpg)
ipxe shell> config (undionly.kpxe -> next-server and filename NOT available, dunno why)

![ipxe efi](https://user-images.githubusercontent.com/94238673/141654432-98cf3174-4b84-4d5d-a31a-0134cddcd702.jpg)
ipxe shell> config (ipxe.efi -> everything received and available to use)

**Comment by bcb01** [comment] 2021-11-13 18:12
![dnsmasq conf](https://user-images.githubusercontent.com/94238673/141654426-b668b835-3698-4c08-88b0-4bcda5dd70ac.jpg)
dnsmasq.conf

![ipxe efi](https://user-images.githubusercontent.com/94238673/141654432-98cf3174-4b84-4d5d-a31a-0134cddcd702.jpg)
ipxe shell config (ipxe.efi)

![undionly kpxe](https://user-images.githubusercontent.com/94238673/141654449-7d3c8c45-2547-40e4-ade9-e375a05fff7d.jpg)
ipxe shell config (undionly.kpxe)

**Comment by n-ice-ch** [comment] 2021-12-29 00:23
I have a similar issue like bcb01 (but maybe they correspond?).
My environment:
- ASUS Router as dumb DHCP-Server
- Debian 11 (as virtualbox guest on a Windows client) with installed and configured dnsmasq server
- BIOS-Client (an additional virtualbox guest) with PXE boot: ${next-server} shows the ip address from ASUS Router instead of the dnsmasq server VM.
--> And I'm confused as it gets load the undionly.kpxe from the dnsmasq server but later on, it does not remember the correct ip for TFTP server?

**Comment by NiKiZe** [comment] 2022-02-25 16:40
When booting you will have 2 DHCP discover phases.
First BIOS/Firmware that runs PXE boot and sends out the request and where you get ipxe.efi or undionly.kpxe back
If there is no embedded script iPXE will then do a second DHCP discover with option 175 set.

Configuration at https://ipxe.org/appnote/proxydhcp should be working for this.

Have you tried to build iPXE with DEBUG=dhcp and grab the output? Also have you done tcpdump? maybe there is bugs in dnsmasq that makes it not send the correct data, even if it looks like it does in it's output?

**Comment by bcb01** [comment] 2022-04-25 08:20
Nope, didn't try these so far. But will do asap. Thx for now for your hint. :)

**Comment by NiKiZe** [comment] 2022-05-05 15:48
Yes that is what I said, if you take a look at the example I posted on ipxe.org you should be able to see this.

I could take another look if you post your full dnsmasq config. But this is not a bug or issue with iPXE (so closing this issue.)

**Closed by NiKiZe** 2022-05-05 15:48 UTC
