### ISSUE TITLE
Error on compile EFI with params CPUID and MEMSI

### ISSUE THREAD

**Issue by francoisjun** [ipxe/ipxe#630] opened 2022-04-06 19:46 UTC
When I compile the EFI version with these settings enabled, an error occurs. In the bios version, this does not happen.

```
# Compile command:

make bin-x86_64-efi/ipxe.efi
```

```
# File config/settings.h

#define CPUID_SETTINGS  /* CPUID settings */
#define MEMMAP_SETTINGS /* Memory map settings */
```

```
# Compile output:

ar: creating bin-x86_64-efi/blib.a
  [HOSTCC] util/elf2efi64
  [VERSION] bin-x86_64-efi/version.ipxe.efi.o
  [LD] bin-x86_64-efi/ipxe.efi.tmp
bin-x86_64-efi/blib.a(librm.o): in function `pm_esp':
(.data.pm_esp+0x0): relocation truncated to fit: R_X86_64_32 against symbol `_estack' defined in .stack section in bin-x86_64-efi/blib.a(stack.o)
bin-x86_64-efi/blib.a(librm.o): in function `real_to_prot':
(.text16.real_to_prot+0x1): relocation truncated to fit: R_X86_64_PC16 against symbol `enable_a20' defined in .text16.early section in bin-x86_64-efi/blib.a(liba20.o)
(.text16.real_to_prot+0x8): relocation truncated to fit: R_X86_64_16 against symbol `rm_ds' defined in .text16.data.rm_ds section in bin-x86_64-efi/blib.a(librm.o)
(.text16.real_to_prot+0x22): relocation truncated to fit: R_X86_64_16 against `.bss16.rm_virt_addrs'
(.text16.real_to_prot+0x2e): relocation truncated to fit: R_X86_64_16 against `.bss16.rm_virt_addrs'
(.text16.real_to_prot+0x33): relocation truncated to fit: R_X86_64_16 against `.bss16.rm_virt_addrs'
(.text16.real_to_prot+0x39): relocation truncated to fit: R_X86_64_16 against `.data16.gdt'
(.text16.real_to_prot+0x58): relocation truncated to fit: R_X86_64_32 against `.text.real_to_prot'
bin-x86_64-efi/blib.a(librm.o): in function `r2p_pmode':
(.text.real_to_prot+0x10): relocation truncated to fit: R_X86_64_32 against `.data.pm_esp'
(.text.real_to_prot+0x17): relocation truncated to fit: R_X86_64_32 against symbol `idtr32' defined in .data.idtr32 section in bin-x86_64-efi/blib.a(librm_mgmt.o)
(.text.real_to_prot+0x1f): additional relocation overflows omitted from the output
make: *** [Makefile.housekeeping:1220: bin-x86_64-efi/ipxe.efi.tmp] Error 1
rm bin-x86_64-efi/version.ipxe.efi.o
```

**Comment by NiKiZe** [comment] 2022-04-06 20:45
That is correct since MEMMAP is not supported on EFI,
Closing this as a duplicate of #429 (feel free to object if you think this is incorrect)

**Closed by NiKiZe** 2022-04-06 20:45 UTC
