### ISSUE TITLE
II followed your README file to compile it in the Ubuntu system, but it encountered an error.

### ISSUE THREAD

**Issue by zhuanshiyan** [ipxe/ipxe#1268] opened 2024-07-28 08:00 UTC
I followed your README file to compile it in the Ubuntu system, but it encountered an error.

here is the error information:

[HOSTCC] util/zbin
util/zbin.c:7:10: fatal error: lzma.h: No such file or directory
    7 | #include <lzma.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile.housekeeping:1427: util/zbin] Error 1

**Comment by NiKiZe** [comment] 2024-07-28 08:42
https://github.com/search?q=repo%3Aipxe%2Fipxe+lzma.h&type=issues

Duplicate of
#821 #189

**Closed by NiKiZe** 2024-07-28 08:42 UTC
