### ISSUE TITLE
Feature request: substring syntax

### ISSUE THREAD

**Issue by alkisg** [ipxe/ipxe#1231] opened 2024-06-02 21:14 UTC
In bash, the `${var:start:count}` syntax allows extracting a substring. It would be useful to have something similar in ipxe, e.g. to apply different settings based on a hostname or mac prefix.

In the meantime, here's a trick to extract the vendor (3 bytes) from the mac address:

> set x ${mac:base64} && set x:ipv4 {x:ipv4} && set x:base64 ${x:string} && set x:hex ${x:hex} && show x

And here's a similar trick to extract the first four characters of the hostname, padded with dashes if it's smaller:

> set x ${hostname}____ && set x:ipv4 ${x:ipv4} && set x ${x:string} && show x

Of course feel free to close the issue if it's not deemed important, compared to the expected binary size increase! 😊

**Comment by NiKiZe** [comment] 2024-06-02 23:13
Unfortunately... closing as duplicate of #1061 https://github.com/ipxe/ipxe/discussions/326#discussioncomment-629914

**Closed by NiKiZe** 2024-06-02 23:13 UTC
