### ISSUE TITLE
Issue with UEFI, unable to reach target in chainload

### ISSUE THREAD

**Issue by AkashPatel2001** [ipxe/ipxe#1051] opened 2023-10-05 11:49 UTC
### Discussed in https://github.com/ipxe/ipxe/discussions/1050

<div type='discussions-op-text'>

<sup>Originally posted by **AkashPatel2001** October  4, 2023</sup>
I am testing my adapter for ipxe, for legacy it is able to reach up to os installation page however UEFI is  failing. i can not blame my driver also because same i have used to download ipxe image. 
Initial observations:
1. Able to load iPXE image from server. 
2. dhcp or ifconf errors out. [No configurations method succeeded.. "Error: Connection timed out"]</div>

**Comment by NiKiZe** [comment] 2023-10-05 12:20
Closing as exact duplicate of #1049 and #1050

So far nothing shows this is an issue with iPXE, until that has been established any issue will be closed.

Dupplicating issues will not help you, quite the opposite!

**Closed by NiKiZe** 2023-10-05 12:20 UTC
