### ISSUE TITLE
VMware Workstation Triple CPU Fault

### ISSUE THREAD

**Issue by rumline** [ipxe/ipxe#664] opened 2022-06-25 18:04 UTC
Attempting to PXE boot either ipxe.efi or snponly.efi using a VMware Workstation 16.2.3 VM on Windows 10 Pro 21H2 build 19044.1766 with an Intel Core i7-6700k CPU causes the VM to crash with what is documented from VMware as a CPU triple fault (https://kb.vmware.com/s/article/2058114).  Tried with both Intel VT-x/EPT and virtualized IOMMU enabled and disabled.

Attempted with both a single vCPU and dual vCPU's with the same result.

Tried with compiling ipxe.efi and snponly.efi on a Rocky 8 VM running in this environment with the same result.

Please advise.

**Comment by stappersg** [comment] 2022-06-25 19:00
When does the crash happen?

Long version of the very same question again:
Which parts of the _network boot process_ do work and does it stop?

**Comment by stappersg** [comment] 2022-06-25 19:00
When does the crash happen?

Long version of the very same question again:
Which parts of the _network boot process_ do work and when does it stop?

**Comment by NiKiZe** [comment] 2022-06-25 23:24
Did any of the attempts to boot include using prebuilt binaries from boot.ipxe.org? (Some compilers might generate broken binaries)

You might have to dig further and find if this is an issue with specific version of VMware, or specific version of ipxe, or the compiler used. Or maybe even the host?
At this stage it sounds like anything could be the cause.

**Comment by rumline** [comment] 2022-06-26 01:34
Happens with prebuilt binaries and custom build binaries.  The crash happens after the initial "Initialising devices" step where a DHCP IP address is requested but at the "2nd initialising hardware" step where it would be "mounting" the tftp server.

More clarity:  I'm using a WDS server.  If you replace the wdsmgfw.efi file in WDS with your own efi boot loader it will begin the PXE process.  The replaced efi bootloader will perform the DHCP process then use DHDP boot option 67 to load the specified bootloader.  So using either "ipxe.efi" or "snponly.efi" for the replaced "wdsmgfw.efi" boot loader to get an IP address works fine.  But then ipxe.fi or snponly.efi is specified in DHCP option 67 and starts to actually load it crashes the VM at "initalising hardware">

**Comment by stappersg** [comment] 2022-06-26 04:57
That is odd.

Thing I'm willing to review are two  `.pcap` files.  One for the _`ipxe.efi` or `snponly.efi` for the replaced `wdsmgfw.efi`_ and the other one _when `ipxe.efi` or `snponly.efi` is specified in DHCP option 67_.  And please tell how the `.pcap`s were created. For that has Original Poster to translate
* Configured [port mirroring](https://en.wikipedia.org/wiki/Port_mirroring) for seeing the _netboot client_
* `tcpdump -w name.pcap ether host MA:Ca:dd:re:ss`

to what is at hand.

**Comment by NiKiZe** [comment] 2022-06-26 08:27
Have you tried using the VMware specific targets? But also do report this to VMware, a bug in their firmware is not unlikely.

**Comment by NiKiZe** [comment] 2022-07-04 17:36
@rumline did you have time to try the vmware specific target ?

**Comment by Hammarskjold** [comment] 2023-06-08 11:06
This is related to #883

**Comment by stappersg** [comment] 2023-07-10 14:28
> This is related to #883

And #883 is closed by #968 about a month ago.

Highlighting @rumline for seeing this feedback request.

**Comment by stappersg** [comment] 2024-08-05 20:44
@rumline a year has past.  Please close this issue, you as creator of the issue have that privilege. Closing this issue will prevent that further human energy is lost on this neglected issue.

**Closed** 2024-08-05 20:49 UTC
